### ISSUE TITLE
Separate domains by a comma in directory table

### ISSUE THREAD

**Issue by adamhsparks** [openplantpathology/OpenPlantPathology#27]
Subject says it all

**Comment by emdelponte** [comment]
I've done that but the comma remained (the way I coded) where there is one domain only.

**Comment by adamhsparks** [comment]
OK, I think we can fix it with an `ifelse`

**Comment by adamhsparks** [comment]
A new line could work as well.

**Comment by emdelponte** [comment]
The new line is nice 👍

**Comment by adamhsparks** [comment]
This still hasn't been fixed yet, reopening. Maybe next month I have more time to work on this.
