### ISSUE TITLE
Main header is slow to load

### ISSUE THREAD

**Issue by adamhsparks** [openplantpathology/OpenPlantPathology#29]
An SVG shouldn't be that slow to load. 

Suggest remove embedded PNG files?

**Comment by adamhsparks** [comment]
Sorry, I'd do this, but I'm not sure where the original files are. When I edit in Inkscape it's apparent that it's not really all SVG graphics.

**Comment by adamhsparks** [comment]
Well, maybe I just didn't ungroup properly? Text doesn't appear as text, perhaps it's been converted to paths in this document? I'll keep poking at it. 👍

**Comment by adamhsparks** [comment]
OK, I didn't ungroup properly. Mea culpa! Text is not embedded as text, but I'm having a go at cleaning up and making it a big lighter.

**Comment by adamhsparks** [comment]
Well, it's maybe, possibly, could be a bit faster now? I don't know, but maybe if text were rendered as text, not as paths, it *might* load faster. Unsure how to do that with an SVG displayed on the web or if it's all that necessary, I'm just being picky.

**Comment by adamhsparks** [comment]
Could just fall back to using the .png file as a header. I've generated it and its ~50% of the size of the SVG. Not as sharp, but definitely acceptable.

**Comment by emdelponte** [comment]
Agree! It looks good.

**Comment by adamhsparks** [comment]
No wonder it loaded faster a few minutes ago. I wondered if it was just my connection. 👍
