### ISSUE TITLE
Domains in directory may contain duplicates

### ISSUE THREAD

**Issue by adamhsparks** [openplantpathology/OpenPlantPathology#31]
"Population biology" and "Population Biology" both appear.

Suggest implementing drop down lists in the spreadsheet with available options to help ensure consistent data entry.

https://productivityspot.com/drop-down-list-in-google-sheets/

**Comment by emdelponte** [comment]
good idea but there will be a problem if the option/domain is not there?

**Comment by adamhsparks** [comment]
I've added a message, 
> "If you do not find your domain(s) listed, please contact Emerson or Adam in Slack. Thanks"

Mouse over the columns now to see it in action.

Does that work?

**Comment by adamhsparks** [comment]
Otherwise we can do lots of work in R with `ifelse` statements and some `toTitleCase` to clean the data.

**Comment by emdelponte** [comment]
Is it implemented already? sorry I did not check the gsheet.

**Comment by adamhsparks** [comment]
yes, easy to undo if we need to.

I've not updated the directory database in R yet.

**Comment by emdelponte** [comment]
it looks perfect to me.

**Comment by adamhsparks** [comment]
Closing as fixed
