### ISSUE TITLE
Handle webpages gracefully

### ISSUE THREAD

**Issue by adamhsparks** [openplantpathology/OpenPlantPathology#5]
If there is no homepage but if there is a Twitter account then you end up with something like:

> NAhttp://www.emr.ac.uk/staff/andrew-armitage-2/NANANA | NAhttps://github.com/adarmitageNANANA

rather than the proper icons

**Comment by emdelponte** [comment]
was this worked out?

**Comment by adamhsparks** [comment]
No, not yet. I'll get there. It will take a bit of thinking to do, but won't be too difficult.

**Comment by emdelponte** [comment]
Ok, just looking through the issues and found this I was not sure what that meant actually.

**Comment by adamhsparks** [comment]
Just display the icons only if a webpage exists. If not, then nothing is displayed.

Previously it displayed "NA" as shown above.

**Comment by adamhsparks** [comment]
Fixed and closed a year later!
