### ISSUE TITLE
Use academicons for ORCID in directory

### ISSUE THREAD

**Issue by adamhsparks** [openplantpathology/OpenPlantPathology#6]
see: https://jpswalsh.github.io/academicons/

**Comment by emdelponte** [comment]
Yes, I have used those in my lab website. 
https://delpontelab.netlify.com/#people

**Comment by emdelponte** [comment]
Should we ask people to include email address? one of the members asked me why ResearchGate was not an option too.

**Comment by adamhsparks** [comment]
I'm OK with ResearchGate as an option as well. Sure!

Can include e-mail address too.

**Comment by adamhsparks** [comment]
So I'm able to close this issue, except now looking at comments we discussed e-mail addresses as well.

Do we need a new field in the form for e-mail address? I can easily insert a link using the member's name. I'm OK without it. It's easy enough to find or contact someone with the information already provided.

**Comment by adamhsparks** [comment]
Will close this issue. If e-mail is to be added we can open a new issue regarding that since this one wandered OT.

Currently e-mail is not in the directory, it would need to be added as an additional field if we were to include it. Easy enough to just use it in the icons below username if we go that route.
