### ISSUE TITLE
Geocode locations for users using ggmap

### ISSUE THREAD

**Issue by adamhsparks** [openplantpathology/OpenPlantPathology#9]
Rather than making the user enter lon/lat values, simply use *ggmap* to geocode the city location.

This makes it much more simple for the user when entering data and makes the data less likely to contain errors when constructing the directory website.

**Comment by emdelponte** [comment]
I have two reasons for not using:

1) I was using it and the function was running every time the site was rendered. When doing my tests I've reached the limit and the coordinates were not displayed.  

2) It is not hard for a person (one time only) get the coordinates from the location he works. Any geocode for the city will bring the lat for the city, not a precise one that we would like to have? 

As to the errors, can we check them when inspecting the gsheet and rendering the site offline and then fix?

**Comment by adamhsparks** [comment]
1. To prevent limits all we need is an API key.

2. Easy to only query the new/empty values, we just need to be smart about how we code it. :)

3. I don't see much reason for exact coordinates. We have institutions listed already and plenty of other information to contact individuals. 

4. Less is more. Less data entry is more attractive.

**Comment by adamhsparks** [comment]
This is implemented in my latest PR, https://github.com/openplantpathology/OpenPlantPathology/pull/10

Using institute as I have should be fairly exact I'd think.

**Comment by adamhsparks** [comment]
Closed with https://github.com/openplantpathology/OpenPlantPathology/pull/10
