### ISSUE TITLE
Change author name Reim->Heim

### ISSUE THREAD

**Issue by ReneHeim** [openplantpathology/OpenPlantPathology#92]
Hi everyone, 

could you please change my name Reim-> Heim?

Could I do this myself? If so, please explain how to implement this change.

Happy Sunday,
Rene

**Comment by adamhsparks** [comment]
Fixed with: https://github.com/openplantpathology/OpenPlantPathology/commit/32c99faabceb40cd2f06a2b26f1684e4b79c0f4d

The easiest way (and it's the way I did it) was you could have edited the file here on GitHub, then you could send a pull request, which @emdelponte or I could have merged.
